events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Route Authentication requests to the auth_service container
        location /api/v1/auth/ {
            proxy_pass http://agri_auth_service:8001/api/v1/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Example for future microservices
        # location /api/v1/irrigation/ {
        #     proxy_pass http://irrigation_service:8002/api/v1/irrigation/;
        #     proxy_set_header Host $host;
        # }
        
        # location /api/v1/crop_health/ {
        #     proxy_pass http://crop_health_service:8003/api/v1/crop_health/;
        #     proxy_set_header Host $host;
        # }
    }
}